#!/bin/bash

# Define the file path
FILE_PATH="/app/.env"

# Create the text with environment variables
TEXT="APP_NAME=${APP_NAME}
APP_ENV=${APP_ENV}
APP_DEBUG=${APP_DEBUG}
APP_URL=${APP_URL}
FRONTEND_URL=${FRONTEND_URL}

LOG_CHANNEL=${LOG_CHANNEL}
LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL}
LOG_LEVEL=${LOG_LEVEL}

DB_CONNECTION=${DB_CONNECTION}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_DATABASE=${DB_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

BROADCAST_DRIVER=${BROADCAST_DRIVER}
CACHE_DRIVER=${CACHE_DRIVER}
FILESYSTEM_DISK=${FILESYSTEM_DISK}
QUEUE_CONNECTION=${QUEUE_CONNECTION}
SESSION_DRIVER=${SESSION_DRIVER}
SESSION_LIFETIME=${SESSION_LIFETIME}

MEMCACHED_HOST=${MEMCACHED_HOST}

REDIS_HOST=${REDIS_HOST}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_PORT=${REDIS_PORT}

MAIL_MAILER=${MAIL_MAILER}
MAIL_HOST=${MAIL_HOST}
MAIL_PORT=${MAIL_PORT}
MAIL_USERNAME=${MAIL_USERNAME}
MAIL_PASSWORD=${MAIL_PASSWORD}
MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
MAIL_FROM_NAME=${MAIL_FROM_NAME}

AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
AWS_BUCKET=${AWS_BUCKET}
AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}

PUSHER_APP_ID=${PUSHER_APP_ID}
PUSHER_APP_KEY=${PUSHER_APP_KEY}
PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
PUSHER_HOST=${PUSHER_HOST}
PUSHER_PORT=${PUSHER_PORT}
PUSHER_SCHEME=${PUSHER_SCHEME}
PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}

VITE_APP_NAME=${VITE_APP_NAME}
VITE_PUSHER_APP_KEY=${VITE_PUSHER_APP_KEY}
VITE_PUSHER_HOST=${VITE_PUSHER_HOST}
VITE_PUSHER_PORT=${VITE_PUSHER_PORT}
VITE_PUSHER_SCHEME=${VITE_PUSHER_SCHEME}
VITE_PUSHER_APP_CLUSTER=${VITE_PUSHER_APP_CLUSTER}
"

# Write the text to the file
echo "$TEXT" >> "$FILE_PATH"
